### ISSUE TITLE
你好,你这个支持其他网站么?

### ISSUE THREAD

**Issue by jambillking** [Foldblade/btcauto-dead#1]
能否修改支持其他网站么???

**Comment by Foldblade** [comment]
这个本身就是写的很弱智的，一分钟一次频率低不说，我自己当时测试一个月下来效果也不甚理想，价格波动如果很大是会死的很惨的。暑假里也就赚了几顿午饭的钱。
倘若其他网站有提供API的话自然是可以的……不过我也没时间去做支持了。
